### ISSUE TITLE
feature to exclude some gits from cloning 

### ISSUE THREAD

**Issue by unl1k3ly** [anshumanbh/git-all-secrets#1]
Hi, 

Thanks for this amazing tool and automation! Much appreciate it.

Sometimes, when cloning company's gits we get lots of "unwanted" repo forked by employees. So, would be possible to exclude it from cloning  the line command ?

Cheers

**Comment by anshumanbh** [comment]
yup, need this! will add to my to-do!

**Comment by anshumanbh** [comment]
This is completed. By default, forks won't be cloned. If you wish to clone forks, just set the flag `cloneForks` to 1. Thanks and please keep providing more feedback!
