### ISSUE TITLE
add support for gitlab

### ISSUE THREAD

**Issue by mlushpenko** [anshumanbh/git-all-secrets#11]
Gitlab is getting more and more popular. Your tool does exactly what we need at our environment, but we have on-premise gitlab, so as I understood from documentation it's not suitable. 

Just a suggestion in case you are actively working on it.

**Comment by anshumanbh** [comment]
git-all-secrets actually just wraps other git finding tools so unless they change, I personally dont have any plans of building a gitlab integration. Closing this for now.
