### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by random-robbie** [anshumanbh/git-all-secrets#12]
Hey dude when i run this against a users repo i am getting the following despite providing a user token?

[![Capture.png](https://s7.postimg.org/ymuoyxw2j/Capture.png)](https://postimg.org/image/yzm354ec7/)

**Comment by random-robbie** [comment]
looks like these repo's are public but need auth to download which is weird.

**Comment by anshumanbh** [comment]
umm, thats really odd. I've never seen that error before on Github.

**Comment by random-robbie** [comment]
ill try find another repo i can present to you as an example to help debug :)

**Comment by anshumanbh** [comment]
I am closing this for now because I have not been able to replicate this.
