### ISSUE TITLE
Scan hangs

### ISSUE THREAD

**Issue by akuryan** [anshumanbh/git-all-secrets#15]
I am trying to scan my repository, but it just hangs without any traces
Here what I get in output:

```The tool will proceed to clone and scan: https://github.com/nameHere/repoName.git only

Starting to clone: https://github.com/nameHere/repoName.git

Username for 'https://github.com': userNameHere
Password for 'https://akuryan@github.com':
Cloning of: https://github.com/nameHere/repoName.git finished

Starting to scan: https://github.com/nameHere/repoName.git
```

And it hangs there in screen for a long while do not outputting anything

**Comment by anshumanbh** [comment]
Couple of questions:

* How big is this repo?
* Is this a private repo? If so, please use the `scanPrivateReposOnly` flag along with providing your SSH key via the mounted volume instead of entering the username/password via the console. 

Let me know if it still doesn't work. Closing this for now.

**Comment by akuryan** [comment]
No, still does not work.
First, I tried with HTTPS connection:
```
docker run -it -v repoName.ssh:/root/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=4f453820f649eb9802df3ac2028f728bad1244aa -repoURL=https://github.com/orgNameHere/repoName.git
The tool will proceed to clone and scan: https://github.com/orgNameHere/repoName.git only

Starting to clone: https://github.com/orgNameHere/repoName.git

Username for 'https://github.com': ^C
```

AS you can see - it wants an auth, but I have 2FA enabled - so, I canceled 

Next, I changed the URL:
```
docker run -it -v repoName.ssh:/root/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=4f453820f649eb9802df3ac2028f728bad1244aa -repoURL=git@github.com:orgNameHere/repoName.git -scanPrivateReposOnly
scanPrivateReposOnly flag is provided with either the user or the repoURL
Checking to see if the SSH key exists or not..
SSH key exists and file size > 0 so continuing..
scanPrivateReposOnly flag is provided along with the repoURL
Checking to see if the repo provided belongs to the user or not..
Repo does not belong to the user whose token is provided. Please provide a valid repoURL that belongs to the user whose token is provided
```

Still no luck :(

I forked repo to myself
```
docker run -it -v repoName.ssh:/root/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=4f453820f649eb9802df3ac2028f728bad1244aa -repoURL=git@github.com:akuryan/repoName.git -scanPrivateReposOnly
scanPrivateReposOnly flag is provided with either the user or the repoURL
Checking to see if the SSH key exists or not..
SSH key exists and file size > 0 so continuing..
scanPrivateReposOnly flag is provided along with the repoURL
Checking to see if the repo provided belongs to the user or not..
Repo belongs to the user provided
The tool will proceed to clone and scan: git@github.com:akuryan/repoName.git only

Starting to clone: git@github.com:akuryan/repoName.git

panic: exit status 128

goroutine 4 [running]:
main.check(0x7cd460, 0xc4201c0260)
        /data/main.go:44 +0x174
main.gitclone(0x7fff3b807e70, 0x20, 0xc4201af120, 0x1b, 0xc4201f4390)
        /data/main.go:57 +0x108
created by main.main
        /data/main.go:756 +0xb4a
```

And got an exception

**Comment by anshumanbh** [comment]
@akuryan 
okay, first things first. I would recommend you to remove the existing Docker image that you have on your system and pull it again from my repo. I've made a bunch of changes since the past couple of days and its possible, you don't have the latest image. 

Please try again and let me know if it still doesn't work. Thanks again!

**Comment by akuryan** [comment]
Still error:
panic: exit status 128

goroutine 34 [running]:
main.check(0x7cd460, 0xc4201ab580)
        /data/main.go:44 +0x174
main.gitclone(0x7fff176f7e70, 0x20, 0xc4201ab360, 0x1b, 0xc4201e63b0)
        /data/main.go:57 +0x108
created by main.main
        /data/main.go:772 +0xb8f

**Comment by anshumanbh** [comment]
@akuryan Exit Status 128 most likely means there is something wrong with the authentication. 

I am going to push a new image soon with some new features. Please try with that image and let me know if you are encountering the same error. I will close this issue for now. If the error still persists in the new image, please send me the exact command you are trying to run.

**Comment by akuryan** [comment]
I removed your image:
akuryan@ownClound-ubuntu:~$ docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
wordpress           latest              3048cd651c28        13 months ago       420 MB
mariadb             latest              4e1ae09402bf        13 months ago       389.8 MB

Then I used following command to scan *private* repository:
docker run -it -v key.ssh:/root/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=4f453820f649eb9802df3ac2028f728bad1244aa -repoURL=git@github.com:akuryan/myPrivateRepo.git -scanPrivateReposOnly


SSH URL
The tool will proceed to clone and scan: git@github.com:akuryan/myPrivateRepo.git only

Starting to clone: git@github.com:akuryan/myPrivateRepo.git

exit status 128: Cloning into '/tmp/repos/singlerepo/myPrivateRepo'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/root/.ssh/id_rsa' are too open.
It is recommended that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private_type: bad permissions
Permission denied (publickey).
fatal: Could not read from remote repository.

Key permissions:
akuryan@ownClound-ubuntu:~$ ls -la | grep key.ssh
-r-------- 1 akuryan akuryan     3247 Dec 11 09:43 key.ssh

So, yes - you are right: problem is with authentication. But I do not know how to fix it

**Comment by anshumanbh** [comment]
Okay, please try this.

Move the private key back to ~/.ssh/key.ssh from the current directory
chmod 400 ~/.ssh/key.ssh

Let me know what happens

**Comment by anshumanbh** [comment]
Also, make sure this private key does not have any passphrase set

**Comment by akuryan** [comment]
Yes, this worked
