### ISSUE TITLE
Is it possible to exclude some folders in repo from scanning?

### ISSUE THREAD

**Issue by akuryan** [anshumanbh/git-all-secrets#17]
We are using [Sitecore Unicorn](https://github.com/kamsar/Unicorn) which serializes data from database to  files on disk and we are checking this files in repository.
File structure includes GUID values which are treated as positives. And we have a lot of files like this, scattered in folders through whole solution.
Hence a question - is it possible to exclude from scanning folders, which names starts/contains/matches given string?

**Comment by anshumanbh** [comment]
There is a PR for this in progress in the truffleHog repo - https://github.com/dxa4481/truffleHog/pull/66#issuecomment-350581807. Once they merge this in, we can get this feature into git-all-secrets as well. Closing this for now since there is not much I can do in this case.
