### ISSUE TITLE
goroutine error 

### ISSUE THREAD

**Issue by unl1k3ly** [anshumanbh/git-all-secrets#2]
Hi,

I'm getting this error when I ran using go as well as the docker.

I've no idea what's that about.

Would you please be able to help ?

Cheers

```Scanning all org repositories now..This may take a while so please be patient

panic: exit status 1

goroutine 1320 [running]:
main.check(0x7c6460, 0xc4201f7560)
	/home/v/Desktop/tools/git-all-secrets/main.go:38 +0x174
main.runGitTools(0xc420db57a0, 0x21, 0xc4202c8880, 0xc420db4ee0, 0x11, 0x7ffeb7d763cc, 0x9)
	/home/v/Desktop/tools/git-all-secrets/main.go:178 +0x1f0
created by main.scanorgrepos
	/home/v/Desktop/tools/git-all-secrets/main.go:279 +0x1bf
exit status 2
```

**Comment by anshumanbh** [comment]
yeah, I'm aware of this problem. This, I think, happens, when you try to run this against a huge org with a ton of repos and users. The users might have tons of repos as well. This, I believe is a problem of the machine where Go spawns so many go routines but the machine is not able to handle it. 

I recommend doing 2 things:
1. Either increase your system's space, memory etc. 
2. Run the tool on lesser attack surface

**Comment by anshumanbh** [comment]
I can't think of any solution to solve this unfortunately. If you are running this inside Docker, I recommend to run it against a smaller set of repos or users..

**Comment by unl1k3ly** [comment]
yeah! I had to add a massive swap file using:

``` 
fallocate /swap -l 4GB
mkswap /swap
swapon /swap
```
VPS had 2GB RAM already. 
I'm scanning user per user. 
Thanks for the tip.

Cheers
