### ISSUE TITLE
Username / Password authentication not working

### ISSUE THREAD

**Issue by sbberk** [anshumanbh/git-all-secrets#20]
Hi, when I run `docker run -it abhartiya/tools_gitallsecrets -token=myToken -org=myOrg -orgOnly=true -toolName=thog`
I get all the repos listed, and then this:

Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com': sbberk
Password for 'https://sbberk@github.com': Username for 'https://github.com': Password for 'https://my_password@github.com':   

And I can't enter my correct username/password to get past this check.  Thanks!

**Comment by anshumanbh** [comment]
Are you trying to scan a repo hosted by Github Enterprise?
Are you trying to scan a private repo? Is this private repo owned by you?
Did you read the instructions on how to use the SSH key?

**Comment by sbberk** [comment]
Thanks, it was a private repo in the org that I had access to, but didn't use the ssh key and that helped!
