### ISSUE TITLE
Issue with scanning repositories using git-all-secrets

### ISSUE THREAD

**Issue by rupsray** [anshumanbh/git-all-secrets#23]
When I am trying to scan all the repositories in our organization, facing the below issue:

> $sudo docker run -it -v ~/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=mytoken -org=myorg -scanPrivateReposOnly
> .........
> .........
> 
> Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions 0755 for '/root/.ssh/id_rsa' are too open.
> It is recommended that your private key files are NOT accessible by others.
> This private key will be ignored.
> key_load_private_type: bad permissions
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> panic: exit status 128
> 
> goroutine 462 [running]:
> main.gitclone(0xc420435b60, 0x2c, 0xc4201fb6a0, 0x1e, 0xc420540a10)
>     /data/main.go:75 +0x387
> main.executeclone.func1.1()
>     /data/main.go:106 +0x4e
> main.enqueueJob.func1(0xc42083d590)
>     /data/main.go:45 +0x27
> created by main.enqueueJob
>     /data/main.go:47 +0x6a

All the files in .ssh folder has 600 permission.

Can you suggest anything to solve this issue? If you can post a video in youtube for this, that will be a great help for everyone. Thank you.

**Comment by anshumanbh** [comment]
By just looking at the command you pasted above, it doesn't look like you are passing the SSH key correctly by mounting the volume - `sudo docker run -it -v ~/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=mytoken -org=myorg -scanPrivateReposOnly`.

Please read the documentation as I have given plenty of examples on how to do this. Feel free to open this again if you still have issues.
