### ISSUE TITLE
orgURL could be another option

### ISSUE THREAD

**Issue by chayanchit** [anshumanbh/git-all-secrets#3]
For enterprise github (specific to a company), there isn't a way to pass both the orgName and enterprise github domain URL. Currently, this component could be used for just one repo at a time for an ORG.

**Comment by anshumanbh** [comment]
Yes, I am aware of that. If you look at the TODO list, the Github Enterprise integration is still pending.

**Comment by narayan8291** [comment]
@anshumanbh : Any updates on the Github Enterprise integration?

**Comment by anshumanbh** [comment]
@narayan8291 Not on my priority list right now unfortunately..

**Comment by anshumanbh** [comment]
@narayan8291 @chayanchit This is now built into the tool. Please review the documentation. Please test it and let me know if you have any issues.

**Comment by anshumanbh** [comment]
I will work on the Github Enterprise integration soon. I mistakingly closed this before thinking the scanning private repos would also work for github enterprise.

**Comment by anshumanbh** [comment]
Github Enterprise is supported now in the next push of the code.
