### ISSUE TITLE
Ask username with token

### ISSUE THREAD

**Issue by Tioborto** [anshumanbh/git-all-secrets#34]
Hello, 
I am testing this product to scan our repositories stored in github (SaaS mode). These deposits are private and public. 
To allow the tool to retrieve the projects, I give it a token with all the accesses but I have the following message:

![image](https://user-images.githubusercontent.com/29703972/46790385-1b552a00-cd3f-11e8-86dc-084ea502ca4d.png)

I use the following command : 
`docker run --rm -it abhartiya/tools_gitallsecrets -org "my_org" -token "my_token" -orgOnly`

**Comment by ctrom** [comment]
I am also experiencing this issue. Did you do something to fix it?

**Comment by outkaj** [comment]
I am having the same issue (even after trying the SSH instructions). @anshumanbh, do you have any suggestions for this?

**Comment by outkaj** [comment]
Never mind, after posting that I literally just fixed the issue by adding `-scanPrivateReposOnly`. @ctrom, does that fix (SSH keys as described in `README` + that flag) help with the issue?

**Comment by ctrom** [comment]
Yes, that does fix the issue for me.
