### ISSUE TITLE
Request for feature - Web Interface option for results

### ISSUE THREAD

**Issue by LampShade42** [anshumanbh/git-all-secrets#40]
Hi, can there be an option for the results to be put into a Bootstrap GUI, like GitRob? 

Example: Having it part of the main program as an argument that spins up Bootstrap and automatically parses the results, or have a second executable that parses the results.txt into Bootstrap.

**Comment by anshumanbh** [comment]
@LampShade42 Yeah, that would absolutely be rad. But, I just don't have the bandwidth for building something like this right now. I do welcome PRs though, if you are interested. Closing this issue for now.
