### ISSUE TITLE
Question regarding performance/efficiency

### ISSUE THREAD

**Issue by fr0stedfl4ke** [anshumanbh/git-all-secrets#42]
While the tool has the ability to scan all possible repo's related to an org, it takes quite a while to complete. I tried using just the trufflehog scanning portion of the tool, but it still manages to take weeks at a time to scan a specific org. I understand it may be due to repo sizes. I'm curious to find out whether there are any ways to fine tune the performance of these scans.

**Comment by anshumanbh** [comment]
@fr0stedfl4ke Hi, thank you for the question. Unfortunately, git-all-secrets is just a wrapper around some of these tools and its as good as the tools themselves, as you can already tell. You can potentially try the `blacklist` flag to leave out the repo that is taking too long to scan, but apart from that, there is not much the tool could do to improve the performance.
