### ISSUE TITLE
Tool requires the github user/pass ?

### ISSUE THREAD

**Issue by vietwow** [anshumanbh/git-all-secrets#8]
Hi, When I try to run git-all-secrets, it requires the github user/pass, but when i watch the video demo, it doesn't.

Even I provided the correct github user/pass, it still can't run :

```
$ docker run --rm -it abhartiya/tools_gitallsecrets:v6 -org=MyOrg -token=d2d2cf23d24d9e267d88d08b34caf48bne895776 -output=results.txt
Since org was provided, the tool will proceed to scan all the org repos, then all the user repos and user gists in a recursive manner
Cloning the repositories of the organization: MyOrg
[...skip repo info...]
Username for 'https://github.com': Username for 'https://github.com': vietwow@gmail.com
Password for 'https://vietwow@gmail.com@github.com': Password for 'https://mypass@github.com':
panic: exit status 128

goroutine 28 [running]:
main.check(0x7fa4c0, 0xc420286780)
	/data/main.go:41 +0x100
main.gitclone(0xc4202feac0, 0x32, 0xc42030a9a0, 0x19, 0xc420280510)
	/data/main.go:54 +0x108
created by main.cloneorgrepos
	/data/main.go:93 +0x405
```

Anyone can help ? Thanks

Best Regards,
VietNC

**Comment by anshumanbh** [comment]
@vietwow This tools only works for public github orgs and repos. Are you trying to run this for public orgs and repos?

**Comment by anshumanbh** [comment]
Also, how did you generate your Github token?

**Comment by vietwow** [comment]
Hi Anshuman,

Thank for your quick reply, ops, I ran it with private repo. So any plan for private repo scanning in the near future ?

Best Regards,
VietNC

**Comment by anshumanbh** [comment]
if its your own private repo, you can generate a Github token from that account and use that token. Since your token will have access to your private repo, it should work. If you are trying to scan somebody else's private repo, then that is something you shouldn't really do, technically speaking.
