### ISSUE TITLE
Tool requires the github user/pass ?

### ISSUE THREAD

**Issue by vietwow** [anshumanbh/git-all-secrets#9]
Hi,

I reopen this issue, firstly, I want to confirm my scanning on my private repo (not other person's repo for any illegitimate purpose).

I have generated token from "https://github.com/settings/tokens" in section "Personal access tokens". But the tool still require to authenticate with github account

Any hint ? Thanks

Best Regards,
VietNC

**Comment by anshumanbh** [comment]
This works. I just tested it now:

docker run -it abhartiya/tools_gitallsecrets:v6 -token <> -repoURL https://github.com/anshumanbh/<private-repo>

Make sure the token you generate has appropriate permissions. Generate a new token and give it all perms, try again. Should work!
